# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'talk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for talk

  target 'talkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'talkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod ‘CocoaAsyncSocket’

end
